### ISSUE TITLE
imagebind_ckpt_path这个应该如何配置？去哪里下载吗？

### ISSUE THREAD

**Issue by yaakua** [DAMO-NLP-SG/Video-LLaMA#47]
如题。我现在需要在本地运行起来，看到文档里面提示需要修改相关配置。但是对其中有几项配置有点疑问，还请帮解答一下。谢谢！
配置文件当中提示有4处内容需要修改，分别是：

``` yaml
# 这个是不是改成合并权重后的vicuna-13b的文件路径？
# 是不是通过执行apply_delta.py脚本得到的那个target目录下的文件？
  llama_model: "ckpt/vicuna-13b/" or "ckpt/vicuna-7b/" 
# 这个我没找到对应的文件目录，我理解应该也是要下载一个模型文件，但是看文档没找到对应的地址。我该如何处理？
  imagebind_ckpt_path: "ckpt/imagebind_path/"
# 这个是不是就是Vision-Language Branch表格当中列出来的模型文件？
# 但我有一个疑问，我应该使用表格当中的哪个呢？如果需要支持中文是不是直接使用finetune-ziya13b-zh?还是pretrain-ziya13b-zh？
  ckpt: path/visual_branch_ckpt/
# 对于这个如果我不需要audio是不是可以不配置？还是说一定要配置？
  ckpt_2: path/audio_branch_ckpt/
```

还请帮我解答一下上面代码当中的注释疑问，再次感谢！
