### ISSUE TITLE
No place to input in the Demo

### ISSUE THREAD

**Issue by ChaofanTao** [DAMO-NLP-SG/Video-LLaMA#57]
Hi, I run the demo by 
```
python demo_audiovideo.py     --cfg-path eval_configs/video_llama_eval_withaudio.yaml  --gpu-id 0
```
It launches successfully, but the input field is stuck and I cannot input words. And the section of 'Video-LLaMA' is null on the interface. I wonder what is the possible solution for it.

<img width="1254" alt="image" src="https://github.com/DAMO-NLP-SG/Video-LLaMA/assets/29567264/2bb63540-73c1-451e-82fb-504797cde1da">

The following is how I fill the file the video_llama_eval_withaudio.yaml.
```
model:
  arch: video_llama
  model_type: pretrain_vicuna
  freeze_vit: True
  freeze_qformer: True
  max_txt_len: 512
  end_sym: "###"
  low_resource: False

  frozen_llama_proj: False

  # models/vicuna-7b-v1 uses llama-7b-hf + vicuna-7b-delta-v0
  llama_model: "models/vicuna-7b-v1" 
  imagebind_ckpt_path: "models/imageBind/"

  fusion_head_layers: 2
  max_frame_pos: 32
  fusion_header_type: "seqTransf"

  ckpt: "models/Video-LLaMA-Series/finetune-vicuna7b-v2.pth" #path/visual_branch_ckpt/  # pretrain: miniGPT4
  ckpt_2: "models/Video-LLaMA-Series/finetune_vicuna7b_audiobranch.pth" #path/audio_branch_ckpt/ # pretrain: ImageBind

datasets:
  webvid:
    vis_processor:
      train:
        name: "alpro_video_eval"
        n_frms: 8
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: video_text_pretrain

```
