### ISSUE TITLE
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]

### ISSUE THREAD

**Issue by mtthwryn** [DAMO-NLP-SG/Video-LLaMA#73]
not sure what is this error a result of, i have downloaded all the weights and edited the paths in the yml file, i am trying to run this locally

**Comment by densechen** [comment]
I have met the same issues

**Comment by xnerhu** [comment]
I have this issue too

**Comment by xnerhu** [comment]
Did you upload wrong vocabulary? https://github.com/huggingface/transformers/issues/20011

```
model:
  arch: video_llama
  model_type: pretrain_vicuna
  freeze_vit: True
  freeze_qformer: True
  max_txt_len: 512
  end_sym: "###"
  low_resource: False

  frozen_llama_proj: False

  # If you want use LLaMA-2-chat,
  # some ckpts could be download from our provided huggingface repo
  # i.e.  https://huggingface.co/DAMO-NLP-SG/Video-LLaMA-2-13B-Finetuned
  # llama_model: "ckpt/llama-2-13b-chat-hf"
  llama_model: 'https://huggingface.co/DAMO-NLP-SG/Video-LLaMA-2-13B-Finetuned/blob/main/VL_LLaMA_2_13B_Finetuned.pth'
  ckpt: 'https://huggingface.co/DAMO-NLP-SG/Video-LLaMA-2-13B-Pretrained/blob/main/AL_LLaMA_2_13B_Pretrained.pth'
  # ckpt: 'path/pretrained_visual_branch_ckpt'   # you can use our pretrained ckpt from https://huggingface.co/DAMO-NLP-SG/Video-LLaMA-2-13B-Pretrained/
  equip_audio_branch: False

  # equip_audio_branch: True  # whether equips the audio branch
  fusion_head_layers: 2
  max_frame_pos: 32
  fusion_header_type: "seqTransf"


datasets:
  webvid:
    vis_processor:
      train:
        name: "alpro_video_eval"
        n_frms: 8
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: video_text_pretrain

```

**Comment by mtthwryn** [comment]
does anyone have a working config file

**Comment by hangzhang-nlp** [comment]
> Did the authors of vllama upload wrong vocabulary? [huggingface/transformers#20011](https://github.com/huggingface/transformers/issues/20011)
> 
> ```
> model:
>   arch: video_llama
>   model_type: pretrain_vicuna
>   freeze_vit: True
>   freeze_qformer: True
>   max_txt_len: 512
>   end_sym: "###"
>   low_resource: False
> 
>   frozen_llama_proj: False
> 
>   # If you want use LLaMA-2-chat,
>   # some ckpts could be download from our provided huggingface repo
>   # i.e.  https://huggingface.co/DAMO-NLP-SG/Video-LLaMA-2-13B-Finetuned
>   # llama_model: "ckpt/llama-2-13b-chat-hf"
>   llama_model: 'https://huggingface.co/DAMO-NLP-SG/Video-LLaMA-2-13B-Finetuned/blob/main/VL_LLaMA_2_13B_Finetuned.pth'
>   ckpt: 'https://huggingface.co/DAMO-NLP-SG/Video-LLaMA-2-13B-Pretrained/blob/main/AL_LLaMA_2_13B_Pretrained.pth'
>   # ckpt: 'path/pretrained_visual_branch_ckpt'   # you can use our pretrained ckpt from https://huggingface.co/DAMO-NLP-SG/Video-LLaMA-2-13B-Pretrained/
>   equip_audio_branch: False
> 
>   # equip_audio_branch: True  # whether equips the audio branch
>   fusion_head_layers: 2
>   max_frame_pos: 32
>   fusion_header_type: "seqTransf"
> 
> 
> datasets:
>   webvid:
>     vis_processor:
>       train:
>         name: "alpro_video_eval"
>         n_frms: 8
>         image_size: 224
>     text_processor:
>       train:
>         name: "blip_caption"
> 
> run:
>   task: video_text_pretrain
> ```

`llama_model: ckpt/llama-2-13b-chat-hf`  **NOT** ``VL_LLaMA_2_13B_Finetuned.pth``

**Comment by hangzhang-nlp** [comment]
> not sure what is this error a result of, i have downloaded all the weights and edited the paths in the yml file, i am trying to run this locally

Try a version of sentencepiece instead? Can you show me the specific configuration file?

**Comment by mtthwryn** [comment]
```
model:
  arch: video_llama
  model_type: pretrain_vicuna
  freeze_vit: True
  freeze_qformer: True
  max_txt_len: 512
  end_sym: "###"
  low_resource: False

  frozen_llama_proj: False

  # If you want use LLaMA-2-chat,
  # some ckpts could be download from our provided huggingface repo
  # i.e.  https://huggingface.co/DAMO-NLP-SG/Video-LLaMA-2-13B-Finetuned
  llama_model: "Video-LLaMA-2-7B-Finetuned/llama-2-7b-chat-hf/"
  imagebind_ckpt_path: "Video-LLaMA-2-7B-Finetuned/imagebind_huge.pth"
  ckpt: 'Video-LLaMA-2-7B-Finetuned/VL_LLaMA_2_7B_Finetuned.pth'   # you can use our pretrained ckpt from https://huggingface.co/DAMO-NLP-SG/Video-LLaMA-2-13B-Pretrained/
  ckpt_2:  'Video-LLaMA-2-7B-Finetuned/AL_LLaMA_2_7B_Finetuned.pth'

  equip_audio_branch: True  # whether equips the audio branch
  fusion_head_layers: 2
  max_frame_pos: 32
  fusion_header_type: "seqTransf"


datasets:
  webvid:
    vis_processor:
      train:
        name: "alpro_video_eval"
        n_frms: 8
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: video_text_pretrain
```

Running with command:
```
python3 demo_audiovideo.py --cfg-path eval_configs/video_llama_eval_withaudio.yaml --model_type llama_v2 --gpu-id 0
```

I'm still getting the same error 
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]
