### ISSUE TITLE
LLaMA2 Video only微调的问题

### ISSUE THREAD

**Issue by CyrilSterling** [DAMO-NLP-SG/Video-LLaMA#89]
您好，在微调llama_v2的video branch时有两个问题，希望您能够解答一下：
1、在使用llamav2进行微调vision branch stage2的时候，visionbranch_stage2_finetune.yaml中下面这里的 `model_type` 应该填 `pretrain_vicuna` 还是 `pretrain_llama_v2`？
```
model:
  arch: video_llama
  model_type: pretrain_vicuna
  freeze_vit: True
  freeze_qformer: True


  # Q-Former
  num_query_token: 32
```
2、使用llamav2进行微调后，在evaluation时，video_llama_eval_only_vision.yaml中下面这里的 `end_sym` 应该填`###`还是`</s>`？
```
model:
  arch: video_llama
  model_type: pretrain_vicuna
  freeze_vit: True
  freeze_qformer: True
  max_txt_len: 512
  end_sym: "###"
  low_resource: False
```
