### ISSUE TITLE
visionbranch stage2 finetune with LLaMA-2 13B, A100 80GB is out of GPU memory.

### ISSUE THREAD

**Issue by joeking11829** [DAMO-NLP-SG/Video-LLaMA#90]
Hi guys,

Thanks for your great works.

When using the 'visionbranch_stage2_finetune.yaml' configuration to fine-tune 'VL_LLaMA_2_13B_Pretrained.pth' on an A100 80GB.
```yaml
  max_epoch: 3
  iters_per_epoch: 1000
  batch_size_train: 4
  batch_size_eval: 4
  num_workers: 4
```
I found that the training program is out of GPU memory.

I only succeeded in starting the training program when I set the batch size to 3.

Do you have any suggestions ?
Thanks !!

**Comment by joeking11829** [comment]
By the way, the "iters_per_epoch" is set to 1000, so during training,
it only uses batch_size * number of GPUs * iters_per_epoch of the total training set.
Each epoch, model will watch 32000 (4 * 8 * 1000) random samples.
Is that correct ?

```yaml
  max_epoch: 3
  iters_per_epoch: 1000
  batch_size_train: 4
  batch_size_eval: 4
  num_workers: 4
```

Thanks !!
